### ISSUE TITLE
购物车价格计算问题

### ISSUE THREAD

**Issue by gadfly3173** [youlaitech/mall-app#1]
/pages/cart/cart.vue

购物车价格计算在非全选的状态下都是错误的，下面给一个参考实现：
```javascript
      changeCart() {
        if (this.cartItems.length === 0) {
          this.empty = true;
          return;
        }

        let checked = true;
        for (let i = 0; i < this.cartItems.length; i++) {
          if (this.cartItems[i].checked === false) {
            checked = false;
            break;
          }
        }
        this.allChecked = checked;
        const checkedItemsList = this.cartItems.filter(item => item.checked)

        if (!checkedItemsList || checkedItemsList.length === 0) {
          this.totalPrice = 0
        } else if (checkedItemsList.length === 1) {
          this.totalPrice = checkedItemsList[0].count * checkedItemsList[0].price;
        } else {
          this.totalPrice = checkedItemsList.reduce((prev, curr) => {
            return prev.price * prev.count + curr.price * curr.count
          })
        }
      },
```

**Comment by haoxianrui** [comment]
@gadfly3173 好的，我把我们本地develop分支和你这边提交的pr合并了，我这边简单的测试了下合并到master分支了。我们这边改动涉及到数据库mall-pms和youlai数据库，mall-oms、mall-pms和youlai-gateway的nacos配置。相应的配置都在项目docs里。提交的pr引入的feign-core解决fegin请求头丢失，我这边测试的时候feign出现incomplete output stream类似这样的错误https://blog.csdn.net/weixin_39835792/article/details/111544551，feign服务端成功但是客户端接收数据报错，具体原因我这边还没深究就先注释了，不清楚你那边的情况。

**Comment by gadfly3173** [comment]
> @gadfly3173 好的，我把我们本地develop分支和你这边提交的pr合并了，我这边简单的测试了下合并到master分支了。我们这边改动涉及到数据库mall-pms和youlai数据库，mall-oms、mall-pms和youlai-gateway的nacos配置。相应的配置都在项目docs里。提交的pr引入的feign-core解决fegin请求头丢失，我这边测试的时候feign出现incomplete output stream类似这样的错误https://blog.csdn.net/weixin_39835792/article/details/111544551，feign服务端成功但是客户端接收数据报错，具体原因我这边还没深究就先注释了，不清楚你那边的情况。

这个是因为feign默认用的java的client的问题，启用httpclient就行了。我还以为这个问题是我特殊情况，就没pr

**Comment by haoxianrui** [comment]
> 这个是因为feign默认用的java的client的问题，启用httpclient就行了。我还以为这个问题是我特殊情况，就没pr

@gadfly3173 嗯， 看来要为引入fegin-core做适配，这个我明天加下就行，早点休息~
