### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by cshaptx4869** [youlaitech/mall-app#3]
大佬 麻烦请教下 HubilderX 能做 vue3-element-admin 那种代码规范吗

**Comment by haoxianrui** [comment]
不清楚，插件市场有对应的插件像 eslint ，但肯定是比不上 VSCode ，目前有不少开源仓库使用 VSCode 替代 HubilderX  作为代码编辑器，真机调试和打包用 HubilderX ，最近打算升级也在纠结如何选择。

**Comment by cshaptx4869** [comment]
感谢 确实HubilderX没vscode好用 纠结…
